---
title: "Multilevel Model Insights"
author: "Gaojia Xu"
date: "11/21/2021"
output:
  pdf_document: default
  html_document: default
---

### Links
The tool created for this homework is a mini-lecture which illustrates the aspect of understanding and use of multilevel models on a dataset. 

The data set used in the mini-lecture comes from The Associated Examining Board in Guildford: Exam scores from http://www.bristol.ac.uk/cmm/learning/support/datasets/. 

The Github repository of related materials, including the Rmd file, ppt and dataset is https://github.com/GaojiaXu/STA610-hw4.

Here is the video link of the mini-lecture is https://youtu.be/c8RYwF-n6Lw. 


### Description

I completed the mini-lecture based on the slide I made, which contains concepts of multilevel models and output from the small case study in R. Detailed explanations are presented in the mini-lecture.

The lecture mentions the concept of multilevel model and  walk through steps of using multilevel model. I divide the lecture into 3 parts, which are "Why do we use a Multilevel Model", "What is a Multilevel Model" and "How to implement a Multilevel Model". At the first section, I introduce the importance and usefulness of using a Multilevel Model. Then secondly, the basic formula is shown to provide a glance of how the simplest model looks like and explain some associated parameters. The third section includes the simple demonstration of how to apply multilevel model on a real-life dataset. 

I further divide the third section to 5 parts, which are background, EDA, model selection, model results, model assessment and limitation. In background, I introduce the dataset, data structure and the research questions. In EDA, I present plots of related variables in the dataset. Then I use AIC and BIC as criteria for choosing best model in model selection, and also write the expression of the model theoretically. Model results section contains fixed effect estimates, correlation between individuals in the same group, , random effects of grouping variable and associated interpretations. Finally, I perform the model assessment and state some limitations.

The procedures of analysis on the dataset is similar to the case study in class. The mini-lecture introduce some concepts about multilevel model itself in addition.

### References
Centre for Multilevel Modelling. http://www.bristol.ac.uk/cmm/learning/support/datasets/
Akande, Olanrewaju(2021). STA 610 Fall 2021. https://sta610-f21.olanrewajuakande.com/syllabus/



